with-expecter: true
issue-845-fix: true

packages:
  server-management-service/internal/infrastructure/security:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/infrastructure/elasticsearch:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/identity/repository:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/identity/service:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/monitoring/domain:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/monitoring/repository:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/monitoring/service:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/monitoring/worker:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/reporting/repository:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/reporting/domain:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/reporting/service:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/server_management/repository:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"
  server-management-service/internal/modules/server_management/service:
    config:
      all: true
      dir: "internal/modules/server_management/handler/grpcserver/mock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      outpkg: "mock"

