FROM golang:1.26-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Expose port 8000 to the outside world
EXPOSE 8000

# Run the executable
CMD ["go", "run", "cmd/api/main.go"]

