// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server-management-service/internal/modules/reporting/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportingRepository is an autogenerated mock type for the ReportingRepository type
type ReportingRepository struct {
	mock.Mock
}

// CreateReportRequest provides a mock function with given fields: ctx, req
func (_m *ReportingRepository) CreateReportRequest(ctx context.Context, req *domain.ReportRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReportRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetServerCountByStatus provides a mock function with given fields: ctx, status
func (_m *ReportingRepository) GetServerCountByStatus(ctx context.Context, status string) (int64, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetServerCountByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReportStatus provides a mock function with given fields: ctx, id, status
func (_m *ReportingRepository) UpdateReportStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReportStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportingRepository creates a new instance of ReportingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportingRepository {
	mock := &ReportingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
