// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMonitoringService is an autogenerated mock type for the MonitoringService type
type MockMonitoringService struct {
	mock.Mock
}

type MockMonitoringService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonitoringService) EXPECT() *MockMonitoringService_Expecter {
	return &MockMonitoringService_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: ctx, serverID, ip, pingSuccess
func (_m *MockMonitoringService) Evaluate(ctx context.Context, serverID string, ip string, pingSuccess bool) error {
	ret := _m.Called(ctx, serverID, ip, pingSuccess)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, serverID, ip, pingSuccess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMonitoringService_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockMonitoringService_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - ip string
//   - pingSuccess bool
func (_e *MockMonitoringService_Expecter) Evaluate(ctx interface{}, serverID interface{}, ip interface{}, pingSuccess interface{}) *MockMonitoringService_Evaluate_Call {
	return &MockMonitoringService_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, serverID, ip, pingSuccess)}
}

func (_c *MockMonitoringService_Evaluate_Call) Run(run func(ctx context.Context, serverID string, ip string, pingSuccess bool)) *MockMonitoringService_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockMonitoringService_Evaluate_Call) Return(_a0 error) *MockMonitoringService_Evaluate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMonitoringService_Evaluate_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockMonitoringService_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMonitoringService creates a new instance of MockMonitoringService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonitoringService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonitoringService {
	mock := &MockMonitoringService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
