// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "server-management-service/internal/modules/server_management/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockMonitoringRepository is an autogenerated mock type for the MonitoringRepository type
type MockMonitoringRepository struct {
	mock.Mock
}

type MockMonitoringRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonitoringRepository) EXPECT() *MockMonitoringRepository_Expecter {
	return &MockMonitoringRepository_Expecter{mock: &_m.Mock}
}

// UpdateServerStatus provides a mock function with given fields: ctx, serverID, newStatus, consecutiveFailures
func (_m *MockMonitoringRepository) UpdateServerStatus(ctx context.Context, serverID string, newStatus domain.ServerStatus, consecutiveFailures int) error {
	ret := _m.Called(ctx, serverID, newStatus, consecutiveFailures)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServerStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ServerStatus, int) error); ok {
		r0 = rf(ctx, serverID, newStatus, consecutiveFailures)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMonitoringRepository_UpdateServerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServerStatus'
type MockMonitoringRepository_UpdateServerStatus_Call struct {
	*mock.Call
}

// UpdateServerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - newStatus domain.ServerStatus
//   - consecutiveFailures int
func (_e *MockMonitoringRepository_Expecter) UpdateServerStatus(ctx interface{}, serverID interface{}, newStatus interface{}, consecutiveFailures interface{}) *MockMonitoringRepository_UpdateServerStatus_Call {
	return &MockMonitoringRepository_UpdateServerStatus_Call{Call: _e.mock.On("UpdateServerStatus", ctx, serverID, newStatus, consecutiveFailures)}
}

func (_c *MockMonitoringRepository_UpdateServerStatus_Call) Run(run func(ctx context.Context, serverID string, newStatus domain.ServerStatus, consecutiveFailures int)) *MockMonitoringRepository_UpdateServerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ServerStatus), args[3].(int))
	})
	return _c
}

func (_c *MockMonitoringRepository_UpdateServerStatus_Call) Return(_a0 error) *MockMonitoringRepository_UpdateServerStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMonitoringRepository_UpdateServerStatus_Call) RunAndReturn(run func(context.Context, string, domain.ServerStatus, int) error) *MockMonitoringRepository_UpdateServerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMonitoringRepository creates a new instance of MockMonitoringRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonitoringRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonitoringRepository {
	mock := &MockMonitoringRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
