// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server-management-service/internal/modules/server_management/domain"

	mock "github.com/stretchr/testify/mock"
)

// MonitoringRepository is an autogenerated mock type for the MonitoringRepository type
type MonitoringRepository struct {
	mock.Mock
}

// UpdateServerStatus provides a mock function with given fields: ctx, serverID, newStatus, consecutiveFailures
func (_m *MonitoringRepository) UpdateServerStatus(ctx context.Context, serverID string, newStatus domain.ServerStatus, consecutiveFailures int) error {
	ret := _m.Called(ctx, serverID, newStatus, consecutiveFailures)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServerStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ServerStatus, int) error); ok {
		r0 = rf(ctx, serverID, newStatus, consecutiveFailures)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMonitoringRepository creates a new instance of MonitoringRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringRepository {
	mock := &MonitoringRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
