// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockObservationLogger is an autogenerated mock type for the ObservationLogger type
type MockObservationLogger struct {
	mock.Mock
}

type MockObservationLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservationLogger) EXPECT() *MockObservationLogger_Expecter {
	return &MockObservationLogger_Expecter{mock: &_m.Mock}
}

// LogObservation provides a mock function with given fields: ctx, serverID, isSuccess
func (_m *MockObservationLogger) LogObservation(ctx context.Context, serverID string, isSuccess bool) error {
	ret := _m.Called(ctx, serverID, isSuccess)

	if len(ret) == 0 {
		panic("no return value specified for LogObservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, serverID, isSuccess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObservationLogger_LogObservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogObservation'
type MockObservationLogger_LogObservation_Call struct {
	*mock.Call
}

// LogObservation is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - isSuccess bool
func (_e *MockObservationLogger_Expecter) LogObservation(ctx interface{}, serverID interface{}, isSuccess interface{}) *MockObservationLogger_LogObservation_Call {
	return &MockObservationLogger_LogObservation_Call{Call: _e.mock.On("LogObservation", ctx, serverID, isSuccess)}
}

func (_c *MockObservationLogger_LogObservation_Call) Run(run func(ctx context.Context, serverID string, isSuccess bool)) *MockObservationLogger_LogObservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockObservationLogger_LogObservation_Call) Return(_a0 error) *MockObservationLogger_LogObservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObservationLogger_LogObservation_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockObservationLogger_LogObservation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObservationLogger creates a new instance of MockObservationLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservationLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservationLogger {
	mock := &MockObservationLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
